# -*- coding: utf-8 -*-
"""Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6eswby1KiRFikolJlyLu9W__UTCGfWW
"""



# Importing useful hashing and encryption libraries...
import rsa
import os
import hashlib



# 2.
# 
import numpy as np
import matplotlib.pyplot as plt

Key = "808670FF00FF08812"
def OTP(key, List):
    """This function takes a key and a list as inputs and performs a hash function on the 
    key and uses the first 6 digits as a one-time-password and appends this value to the list"""
    OTP = str(int(hashlib.sha256((key).encode("utf-8")).hexdigest(),16))[:6]
    List.append(OTP)
    return List

OTP



# The number of identical OTPs are there. A raw number not a percentage.





